version: '3.10'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: nest
    networks:
       - rainnet

networks:
  rainnet:
    driver: bridge
